# Generated by Django 4.2 on 2023-10-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="closed_at",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="branch",
            name="open_at",
            field=models.TimeField(),
        ),
    ]
