# Generated by Django 4.2 on 2023-10-26 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0002_alter_branch_closed_at_alter_branch_open_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guests", models.IntegerField(default=1)),
                ("time", models.TimeField(max_length=50)),
                ("day", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In_progress", "In_progress"),
                            ("Reserved", "Reserved"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch",
                        to="reservations.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
