# Generated by Django 4.2 on 2023-10-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="guests_per_half_an_hour",
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("In_progres", "In_progres"),
                    ("Confirmed", "Confirmed"),
                    ("Canceled", "Canceled"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(),
        ),
    ]
