# Generated by Django 4.2 on 2023-10-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_user_name_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
