# Generated by Django 4.2 on 2023-10-26 10:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_user_location_location_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="country",
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
