# Generated by Django 4.2 on 2023-10-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_location_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.location",
            ),
        ),
    ]
