# Generated by Django 4.2 on 2023-10-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="is_optional",
            field=models.BooleanField(default=False),
        ),
    ]
