# Generated by Django 4.2 on 2023-10-14 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0003_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_fav",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="sale",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
