# Generated by Django 4.2 on 2023-10-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="6DF565857", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="C6DB117CDE49FE8", max_length=15),
        ),
    ]
