# Generated by Django 4.2 on 2023-10-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="41161A2FF", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="1E258AC8FC877A5", max_length=15),
        ),
    ]
