# Generated by Django 4.2 on 2023-10-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="38FC8A2321", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="A6F291E639D82ED", max_length=15),
        ),
    ]
