# Generated by Django 4.2 on 2023-10-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="68A618A853", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="784A4FB43161DC79D786", max_length=20),
        ),
    ]
