# Generated by Django 4.2 on 2023-10-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="73E95EFE9B", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="BDA1E76E6FF84B398789", max_length=20),
        ),
    ]
