# Generated by Django 4.2 on 2023-10-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="BA7245B6CE", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="AA5B3976B4FFEC2174DB", max_length=20),
        ),
    ]
