# Generated by Django 4.2 on 2023-10-23 00:46

from django.db import migrations, models
import orders.utils


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default=orders.utils.generate_code, max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(
                default=orders.utils.cart_generate_code, max_length=20
            ),
        ),
    ]
